name: Generate Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build

    - name: Generate TypeDoc (Markdown)
      run: npm run docs:api

    - name: Fetch OpenAPI spec
      run: curl -L https://api.tenantos.com/docs/openapi.yaml -o openapi.yaml

    - name: Generate Redoc (OpenAPI HTML)
      run: |
        if [ -f openapi.yaml ]; then
          npm run docs:openapi || echo "Redoc generation failed; continuing"
        else
          echo "No openapi.yaml found; skipping Redoc"
        fi
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        destination_dir: .
